# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

resources:
- repo: self

variables:
  buildDirectory: 'build'

stages:
- stage: Build
  displayName: Build and Publish
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: CmdLine@2
      inputs:
        script: yarn install
    - task: CmdLine@2
      inputs:
        script: yarn run build
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(buildDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'